"""Offline libretro / No-Intro index: bundled compact JSON + raw DAT parsing.

The index is the *provider* side of the metadata layer.  It is built **once**
into two in-memory maps (SHA-1 preferred, CRC32 fallback), so a hash lookup
never re-reads or re-parses a file.  Two input dialects are understood:

* the bundled **compact JSON** index (``vajsave/data/libretro/<platform>.json``)
  generated by ``tools/build_metadata_index.py`` -- the default, offline path;
* a real **No-Intro / Logiqx XML DAT** (``.dat``/``.xml``) that a user dropped
  next to the library or pointed the app at in settings.

Only cartridge platforms the app actually identifies by ROM digest
(GB/GBC/GBA/NDS) are indexed; a digest recorded for any other platform can
only ever return ``None``.  Malformed, missing or unreadable files degrade to
"nothing indexed" rather than raising. Bundled compact JSON currently ships
for GBA/NDS; GB/GBC accept a user DAT under ``libretro_dir`` or a generated
``gb.json``/``gbc.json``.
"""

from __future__ import annotations

import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple, Union

from ..identity.naming import extract_region, normalize_title
from .models import SOURCE_LIBRETRO, GameMetadata

# Platforms the metadata layer can answer for.  Everything else is out of scope
# by design: the other consoles are identified by title id, not ROM digest.
SUPPORTED_PLATFORMS: Tuple[str, ...] = ("gba", "nds", "gb", "gbc")

# On-disk format of the bundled compact index.
INDEX_FORMAT = "vajsave.libretro-index"
INDEX_FORMAT_VERSION = 1

# Substrings found in a datafile header/name that map to a supported platform.
_PLATFORM_MARKERS: Tuple[Tuple[str, str], ...] = (
    ("game boy advance", "gba"),
    ("gameboy advance", "gba"),
    ("game boy color", "gbc"),
    ("gameboy color", "gbc"),
    ("nintendo ds", "nds"),
    ("nintendo - ds", "nds"),
    ("game boy", "gb"),
    ("gameboy", "gb"),
    ("gba", "gba"),
    ("gbc", "gbc"),
    ("nds", "nds"),
)


def _normalize_hex(value: Optional[str], width: int) -> Optional[str]:
    """Canonicalise a hex digest: lowercase, no ``0x``, zero-padded.

    Returns ``None`` for a missing or non-hex value so a bad field is simply not
    indexed instead of poisoning the map with a bogus key.
    """
    if value is None:
        return None
    text = str(value).strip().lower().replace("0x", "")
    if not text:
        return None
    try:
        number = int(text, 16)
    except ValueError:
        return None
    if number < 0:
        return None
    return format(number, "0{}x".format(width))


# A cartridge game code is exactly four alphanumeric characters (e.g. ``BPEE``).
# No-Intro DATs also carry placeholder/sentinel serials such as ``!none`` and
# ``!n/a``; those must never become index keys.
_SERIAL_RE = re.compile(r"^[A-Z0-9]{4}$")
_INVALID_SERIALS = frozenset({"!NONE", "!N/A", "N/A", "NONE", "NULL"})

# Parenthetical/bracketed metadata tags (region, language list, revision, ...).
_TAG_RE = re.compile(r"[\(\[]([^\)\]]*)[\)\]]")

# Variant tags that mark a non-retail build.  A same-family fallback prefers a
# real release over a beta/proto/demo when several share one game code.
_NON_RETAIL_TAGS = (
    "beta",
    "proto",
    "demo",
    "sample",
    "kiosk",
    "unl",
    "program",
    "test",
    "piracy",
)


def _normalize_serial(value: Optional[str]) -> Optional[str]:
    """Canonicalise a cartridge game code, or ``None`` when it is not usable.

    Upper-cased and stripped, then required to be exactly four alphanumeric
    characters.  Sentinel/placeholder serials and over-long No-Intro oddities
    are rejected so they cannot collide with a real ROM header game code.
    """
    if value is None:
        return None
    text = str(value).strip().upper()
    if not text or text in _INVALID_SERIALS:
        return None
    if not _SERIAL_RE.match(text):
        return None
    return text


def _family_key(title: str) -> str:
    """Region/rev/variant-free title key used to group one serial's releases.

    ``normalize_title`` strips every parenthetical tag, so all regional and
    revision variants of the same game share one key while genuinely different
    titles (a serial collision) stay apart.
    """
    return normalize_title(title)


def _tag_tokens(title: str) -> List[str]:
    tokens: List[str] = []
    for match in _TAG_RE.finditer(str(title or "")):
        for part in re.split(r"[,\s]+", match.group(1)):
            if part:
                tokens.append(part.lower())
    return tokens


def _is_non_retail(metadata: GameMetadata) -> bool:
    """Whether a record's tags explicitly mark a non-retail build.

    ``beta``/``proto``/``demo``/... are unambiguous build markers, so a record
    carrying one is never treated as a real release.  Used both to rank variants
    inside one family and to discard whole non-retail families during the
    cross-family serial fallback.
    """
    tokens = _tag_tokens(metadata.canonical_title)
    return any(token.startswith(prefix) for token in tokens for prefix in _NON_RETAIL_TAGS)


def _is_retail_family(variants: Iterable[GameMetadata]) -> bool:
    """Whether a family contains at least one real (retail) release.

    A family whose every variant is explicitly non-retail (e.g. only a demo) is
    discarded during the cross-family fallback; a family with one retail variant
    survives even if it also carries betas/protos alongside it.
    """
    return any(not _is_non_retail(item) for item in variants)


def _variant_sort_key(metadata: GameMetadata):
    """Deterministic ranking of same-family variants: retail first, then fewest tags."""
    tokens = _tag_tokens(metadata.canonical_title)
    return (
        _is_non_retail(metadata),
        len(tokens),
        metadata.canonical_title,
        metadata.identity_key,
    )


# A header-title token shorter than this is too generic ("ds", "ph", "2") to
# safely prove which family an ambiguous game code refers to.
_MIN_TITLE_HINT_TOKEN = 4


def _title_hint_tokens(title: Optional[str]) -> List[str]:
    """Distinctive, normalised tokens of a ROM header title."""
    return [
        token
        for token in normalize_title(str(title or "")).split()
        if len(token) >= _MIN_TITLE_HINT_TOKEN
    ]


def _family_matches_title(family_key: str, header_title: Optional[str]) -> bool:
    """Whether a header title distinctively names the family behind ``family_key``.

    Comparison is on normalised tokens of at least four characters so short,
    generic fragments (``ds``, ``64``) cannot create a false match.  A token
    counts when it appears verbatim in the family title or when one is a prefix
    of the other -- the second case absorbs header titles that glue words
    together (``MARIO64DS`` vs the family token ``mario``) or truncate at the
    twelve-byte header limit.  An empty/weak title yields no tokens and so never
    matches, keeping ambiguous game codes unresolved.
    """
    hints = _title_hint_tokens(header_title)
    if not hints:
        return False
    family_tokens = [
        token
        for token in family_key.split()
        if len(token) >= _MIN_TITLE_HINT_TOKEN
    ]
    if not family_tokens:
        return False
    return any(
        hint == token or hint.startswith(token) or token.startswith(hint)
        for hint in hints
        for token in family_tokens
    )


def detect_platform(*names: Optional[str]) -> Optional[str]:
    """Best-effort platform from a datafile header/filename (or ``None``)."""
    for name in names:
        if not name:
            continue
        haystack = str(name).strip().lower()
        for marker, platform in _PLATFORM_MARKERS:
            if marker in haystack:
                return platform
    return None


def _identity_key(platform: str, sha1: Optional[str], crc32: Optional[str]) -> str:
    if sha1:
        return f"{platform}:sha1:{sha1}"
    if crc32:
        return f"{platform}:crc32:{crc32}"
    return f"{platform}:name:"


def external_ids_for(serial: Optional[str], nointro_id: Optional[str]) -> Optional[Dict[str, str]]:
    """Build the descriptive ``external_ids`` map from a DAT record."""
    ids: Dict[str, str] = {}
    if serial and serial.strip() and serial.strip() != "n/a":
        ids["serial"] = serial.strip()
    if nointro_id and nointro_id.strip():
        ids["nointro"] = nointro_id.strip()
    return ids or None


class LibretroIndex:
    """An in-memory ``SHA-1``/``CRC32`` -> :class:`GameMetadata` lookup."""

    def __init__(self) -> None:
        self._by_sha1: Dict[str, GameMetadata] = {}
        self._by_crc: Dict[str, GameMetadata] = {}
        self._by_serial: Dict[str, List[GameMetadata]] = {}
        self._games: int = 0

    # -- building ------------------------------------------------------------

    def add(
        self,
        *,
        platform: str,
        canonical_title: str,
        sha1: Optional[str] = None,
        crc32: Optional[str] = None,
        region: Optional[str] = None,
        serial: Optional[str] = None,
        nointro_id: Optional[str] = None,
        source: str = SOURCE_LIBRETRO,
    ) -> None:
        plat = (platform or "").strip().lower()
        if plat not in SUPPORTED_PLATFORMS or not canonical_title:
            return
        norm_sha1 = _normalize_hex(sha1, 40) if sha1 else None
        norm_crc = _normalize_hex(crc32, 8) if crc32 else None
        if not norm_sha1 and not norm_crc:
            return
        metadata = GameMetadata(
            identity_key=_identity_key(plat, norm_sha1, norm_crc),
            platform=plat,
            canonical_title=canonical_title,
            region=region if region is not None else extract_region(canonical_title),
            external_ids=external_ids_for(serial, nointro_id),
            source=source,
        )
        if norm_sha1:
            self._by_sha1[norm_sha1] = metadata
        if norm_crc:
            self._by_crc[norm_crc] = metadata
        norm_serial = _normalize_serial(serial)
        if norm_serial:
            self._by_serial.setdefault(norm_serial, []).append(metadata)
        self._games += 1

    def load_json_file(self, path: Union[Path, str]) -> int:
        """Load a compact index file. Returns the number of records added."""
        p = Path(path)
        try:
            raw = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError, UnicodeDecodeError):
            return 0
        if not isinstance(raw, dict) or raw.get("format") != INDEX_FORMAT:
            return 0
        platform = str(raw.get("platform") or "").strip().lower()
        if platform not in SUPPORTED_PLATFORMS:
            platform = detect_platform(str(raw.get("platform") or ""), p.name) or ""
        if platform not in SUPPORTED_PLATFORMS:
            return 0
        records = raw.get("records")
        if not isinstance(records, list):
            return 0
        added = 0
        for record in records:
            if not isinstance(record, (list, tuple)) or len(record) < 3:
                continue
            sha1 = str(record[0] or "")
            crc32 = str(record[1] or "")
            title = str(record[2] or "")
            serial = str(record[3] or "") if len(record) > 3 else ""
            nointro_id = str(record[4] or "") if len(record) > 4 else ""
            if not title:
                continue
            self.add(
                platform=platform,
                canonical_title=title,
                sha1=sha1,
                crc32=crc32,
                serial=serial,
                nointro_id=nointro_id,
            )
            added += 1
        return added

    def load_file(self, path: Union[Path, str], *, platform: Optional[str] = None) -> int:
        """Load one file, choosing the parser from its ``.json`` suffix.

        Returns the number of records added; ``0`` for anything unusable.
        """
        p = Path(path)
        if p.suffix.lower() == ".json":
            return self.load_json_file(p)
        return self.load_xml_file(p, platform=platform)

    def load_xml_file(self, path: Union[Path, str], *, platform: Optional[str] = None) -> int:
        """Parse one Logiqx XML datafile. Returns the number of records added.

        ``platform`` overrides header/filename detection; when neither yields a
        supported platform the file contributes nothing.
        """
        p = Path(path)
        try:
            tree = ET.parse(p)
        except (OSError, ET.ParseError, ValueError):
            return 0
        root = tree.getroot()
        if root is None:
            return 0
        header = root.find("header")
        header_names: List[str] = []
        if header is not None:
            for tag in ("name", "description"):
                node = header.find(tag)
                if node is not None and node.text:
                    header_names.append(node.text)
        resolved = (platform or "").strip().lower() or detect_platform(*header_names, p.name)
        if resolved not in SUPPORTED_PLATFORMS:
            return 0
        added = 0
        for game in list(root):
            if game.tag not in ("game", "machine"):
                continue
            name = (game.get("name") or "").strip()
            if not name:
                description = game.find("description")
                name = (description.text or "").strip() if description is not None else ""
            if not name:
                continue
            nointro_id = (game.get("id") or "").strip()
            for rom in game.findall("rom"):
                added += self._add_rom(
                    platform=resolved,
                    name=name,
                    nointro_id=nointro_id,
                    rom=rom,
                )
        return added

    def _add_rom(self, *, platform: str, name: str, nointro_id: str, rom) -> int:
        sha1 = _normalize_hex(rom.get("sha1"), 40)
        crc32 = _normalize_hex(rom.get("crc"), 8)
        if not sha1 and not crc32:
            return 0
        self.add(
            platform=platform,
            canonical_title=name,
            sha1=sha1,
            crc32=crc32,
            serial=rom.get("serial"),
            nointro_id=nointro_id,
        )
        return 1

    def load_directory(
        self,
        directory: Union[Path, str],
        *,
        platform: Optional[str] = None,
        patterns: Iterable[str] = ("*.json", "*.dat", "*.xml"),
    ) -> int:
        """Load every matching datafile under ``directory`` (non-recursive)."""
        base = Path(directory)
        try:
            if not base.is_dir():
                return 0
        except OSError:
            return 0
        total = 0
        seen: set = set()
        for pattern in patterns:
            for candidate in sorted(base.glob(pattern)):
                try:
                    key = str(candidate.resolve())
                except OSError:
                    key = str(candidate)
                if key in seen:
                    continue
                seen.add(key)
                total += self.load_file(candidate, platform=platform)
        return total

    @classmethod
    def from_paths(
        cls,
        paths: Iterable[Union[Path, str]],
        *,
        platform: Optional[str] = None,
    ) -> "LibretroIndex":
        index = cls()
        for path in paths:
            p = Path(path)
            try:
                if p.is_dir():
                    index.load_directory(p, platform=platform)
                else:
                    index.load_file(p, platform=platform)
            except OSError:
                continue
        return index

    # -- lookup --------------------------------------------------------------

    def lookup(
        self,
        *,
        platform: str,
        crc32: Optional[str] = None,
        sha1: Optional[str] = None,
    ) -> Optional[GameMetadata]:
        """Resolve a ROM by digest, or ``None`` when unknown/unsupported.

        SHA-1 is preferred over CRC32 because it is collision-resistant; a digest
        recorded under a *different* platform never satisfies the request.
        """
        wanted = (platform or "").strip().lower()
        if wanted not in SUPPORTED_PLATFORMS:
            return None
        norm_sha1 = _normalize_hex(sha1, 40) if sha1 else None
        norm_crc = _normalize_hex(crc32, 8) if crc32 else None
        for digest, table in ((norm_sha1, self._by_sha1), (norm_crc, self._by_crc)):
            if not digest:
                continue
            found = table.get(digest)
            if found is not None and found.platform == wanted:
                return found
        return None

    def lookup_serial(
        self,
        *,
        platform: str,
        serial: Optional[str],
        title: Optional[str] = None,
    ) -> Optional[GameMetadata]:
        """Conservative **digest-miss** fallback keyed by cartridge game code.

        Both indexed cartridge platforms (GBA and NDS) are understood.  A code
        that maps to a single *family* of games resolves to a deterministic
        member of that family (see :func:`_variant_sort_key`); regional/revision
        variants of one title therefore collapse to one release.

        A code shared by several families is normally a real serial collision.
        Two conservative escapes exist:

        * a strong ``title`` (the ROM header title) that names **exactly one**
          family resolves to that family -- this is how a patched ROM such as the
          Chinese Zelda: Phantom Hourglass (code ``AZEJ``) is disambiguated from
          an unrelated family that reused the code.  An empty, weak or
          conflicting title matches zero or several families and stays
          unresolved;
        * for GBA only, when every family but one is *explicitly* non-retail
          (e.g. a demo/proto that reused the code), the single remaining retail
          family is trusted -- this is what lets a patched ROM such as the
          Chinese ``Gyakuten Saiban 2`` (code ``A3GJ``, shared with a ``Gyakuten
          Saiban 3`` demo) resolve.  Two or more distinct retail families stay
          ambiguous and still return ``None``.
        """
        wanted = (platform or "").strip().lower()
        if wanted not in SUPPORTED_PLATFORMS:
            return None
        normalized = _normalize_serial(serial)
        if not normalized:
            return None
        candidates = [
            item for item in self._by_serial.get(normalized, ()) if item.platform == wanted
        ]
        if not candidates:
            return None
        families: Dict[str, List[GameMetadata]] = {}
        for item in candidates:
            families.setdefault(_family_key(item.canonical_title), []).append(item)
        if len(families) == 1:
            return min(next(iter(families.values())), key=_variant_sort_key)
        # A shared game code: try the header title first, then the GBA retail rule.
        if title:
            titled = {
                key: variants
                for key, variants in families.items()
                if _family_matches_title(key, title)
            }
            if len(titled) == 1:
                return min(next(iter(titled.values())), key=_variant_sort_key)
            # Zero or several matches fall through to the platform-specific rule.
        if wanted == "gba":
            # A shared game code is normally a real serial collision and must
            # stay unresolved.  The one safe exception is a code shared by
            # exactly one retail family plus one or more families that are
            # *explicitly* non-retail (a demo/proto/beta that reused the code).
            # Only then can the single retail family be trusted; two or more
            # distinct retail families remain ambiguous and return ``None``.
            retail = {
                key: variants
                for key, variants in families.items()
                if _is_retail_family(variants)
            }
            if len(retail) != 1:
                return None
            return min(next(iter(retail.values())), key=_variant_sort_key)
        return None

    # -- introspection -------------------------------------------------------

    @property
    def games(self) -> int:
        return self._games

    def __len__(self) -> int:
        return self._games

    def __bool__(self) -> bool:
        return self._games > 0


__all__ = [
    "LibretroIndex",
    "SUPPORTED_PLATFORMS",
    "INDEX_FORMAT",
    "INDEX_FORMAT_VERSION",
    "detect_platform",
    "external_ids_for",
]
